declare @USER_ID_V INT,
        @RUR_ID_V INT;
begin
  CREATE TABLE WEB_TOKEN(
		[ID] [bigint] IDENTITY(1,1) NOT NULL,
		[PARAMETERS_LIST] [nvarchar](4000) NULL,
		[GUID] [nvarchar](36) NOT NULL,
		[ACCDATE] [datetime] NOT NULL
	 CONSTRAINT [PK_web_token] PRIMARY KEY CLUSTERED 
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY];	

  SELECT @USER_ID_V=(MAX(U.USER_ID)+1)
  FROM REP_USERS U;
  SET IDENTITY_INSERT [REP_USERS] ON;
  insert into REP_USERS (USER_ID, FIO, LOGIN, PASSWORD, EMAIL, PHONE, SOL)
  values (@USER_ID_V, N'Администратор РВК.П.Реакт', N'admin_r', N'$2a$10$d18ZjBRTh34uP2UUdQrxDeyY52L3pvLxA.Ul3/dld/yyRb/4qucA6', null, null, 3);
  SET IDENTITY_INSERT [REP_USERS] Off;
  SET IDENTITY_INSERT [REP_USERS_RIGHTS] On;
  SELECT @RUR_ID_V=(MAX(R.RUR_ID)+1)
  FROM REP_USERS_RIGHTS R;
  insert into REP_USERS_RIGHTS (RUR_ID, USER_ID, RIGHT_ID)
  values (@RUR_ID_V, @USER_ID_V, 1);
  SELECT @RUR_ID_V=(MAX(R.RUR_ID)+1)
  FROM REP_USERS_RIGHTS R;
  insert into REP_USERS_RIGHTS (RUR_ID, USER_ID, RIGHT_ID)
  values (@RUR_ID_V, @USER_ID_V, 2);
  SELECT @RUR_ID_V=(MAX(R.RUR_ID)+1)
  FROM REP_USERS_RIGHTS R;
  insert into REP_USERS_RIGHTS (RUR_ID, USER_ID, RIGHT_ID)
  values (@RUR_ID_V, @USER_ID_V, 1002);
  SELECT @RUR_ID_V=(MAX(R.RUR_ID)+1)
  FROM REP_USERS_RIGHTS R;
  insert into REP_USERS_RIGHTS (RUR_ID, USER_ID, RIGHT_ID)
  values (@RUR_ID_V, @USER_ID_V, 1004);
  SET IDENTITY_INSERT [REP_USERS_RIGHTS] Off;
end;
GO
