CREATE TABLE `rep_users` (
  `USER_ID` INT(17) NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(500) NOT NULL,
  `LOGIN` VARCHAR(200) NOT NULL,
  `PASSWORD` VARCHAR(200) NOT NULL,
  `EMAIL` VARCHAR(500) NULL,
  `PHONE` VARCHAR(100) NULL,
  `SOL` TINYINT(2) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE,
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC) VISIBLE,
  UNIQUE INDEX `LOGIN_PWD` (`LOGIN` ASC, `PASSWORD` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `rep_rights` (
  `RIGHTS_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(500) NOT NULL,
  `SYSNAME` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`RIGHTS_ID`),
  UNIQUE INDEX `RIGHTS_ID_UNIQUE` (`RIGHTS_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `rep_users_rights` (
  `RUR_ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(17) NOT NULL,
  `RIGHT_ID` INT(10) NOT NULL,
  PRIMARY KEY (`RUR_ID`),
  UNIQUE INDEX `idREP_USERS_RIGHTS_UNIQUE` (`RUR_ID` ASC) VISIBLE,
  UNIQUE INDEX `USER_ID_RIGHT_ID` (`USER_ID` ASC, `RIGHT_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `rep_calc_olap` (
  `CONTRACT_REFID` VARCHAR(10) NULL,
  `JUR_LS_REFID` VARCHAR(10) NULL,
  `PAYER_SNAME` VARCHAR(10) NULL,
  `ACCDATE` DATETIME NULL,
  `ENDACCDATE` DATETIME NULL,
  `INVOICE_DATE` DATETIME NULL,
  `SERVICE` VARCHAR(17) NULL,
  `CALC_VOLUME` DECIMAL(28,2) NULL,
  `CALC_COST` DECIMAL(28,2) NULL,
  `CALC_NET` DECIMAL(28,2) NULL,
  `TARIFF` VARCHAR(4) NULL,
  `VAT_RATE` DECIMAL(28,2) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
