/*!!!Обязательно установка опции lower_case_table_names = 1
https://askubuntu.com/questions/1261422/how-to-install-mysql-8-0-with-lower-case-table-names-1-on-ubuntu-server-20-04-lt*/
CREATE TABLE `rep_users` (
  `USER_ID` INT(17) NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(500) NOT NULL,
  `LOGIN` VARCHAR(200) NOT NULL,
  `PASSWORD` VARCHAR(200) NOT NULL,
  `EMAIL` VARCHAR(500) NULL,
  `PHONE` VARCHAR(100) NULL,
  `SOL` TINYINT(2) NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC) VISIBLE,
  UNIQUE INDEX `LOGIN_PWD` (`LOGIN` ASC, `PASSWORD` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `rep_rights` (
  `RIGHTS_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(500) NOT NULL,
  `SYSNAME` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`RIGHTS_ID`) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `rep_users_rights` (
  `RUR_ID` BIGINT(19) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(17) NOT NULL,
  `RIGHT_ID` INT(10) NOT NULL,
  PRIMARY KEY (`RUR_ID`),
  UNIQUE INDEX `USER_ID_RIGHT_ID` (`USER_ID` ASC, `RIGHT_ID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

/*CREATE TABLE `rep_calc_olap` (
  `CONTRACT_REFID` VARCHAR(10) NULL,
  `JUR_LS_REFID` VARCHAR(10) NULL,
  `PAYER_SNAME` VARCHAR(10) NULL,
  `ACCDATE` DATETIME NULL,
  `ENDACCDATE` DATETIME NULL,
  `INVOICE_DATE` DATETIME NULL,
  `SERVICE` VARCHAR(17) NULL,
  `CALC_VOLUME` DECIMAL(28,2) NULL,
  `CALC_COST` DECIMAL(28,2) NULL,
  `CALC_NET` DECIMAL(28,2) NULL,
  `TARIFF` VARCHAR(4) NULL,
  `VAT_RATE` DECIMAL(28,2) NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;*/

INSERT INTO REP_RIGHTS (RIGHTS_ID, NAME, SYSNAME)
   VALUES (1, 'Редактирование формы', 'Edite'),
		  (2, 'Просмотр формы', 'View'),
		  (1002, 'Удаление формы', 'Delete'),
		  (1004, 'Администрирование пользователей', 'Admin');
INSERT INTO REP_USERS (FIO, LOGIN, PASSWORD, EMAIL, PHONE, SOL)
   VALUES ('admin', 'admin', '$2a$10$A.6oNVSpds0uiBe9PwjgBe/.HQ.r5M.4O/rFXw5Rit.uk3O6Rw06C', NULL, NULL, 1);
SET @USER_ID_V := LAST_INSERT_ID();
INSERT INTO REP_USERS_RIGHTS (USER_ID, RIGHT_ID)
   VALUES (@USER_ID_V, 1),
		  (@USER_ID_V, 2),
		  (@USER_ID_V, 1002),
		  (@USER_ID_V, 1004);
